AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance.

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro" # Change instance type if needed
      ImageId: "ami-0c02fb55956c7d316" # Amazon Linux 2 AMI ID (Region-specific, replace if necessary)
      KeyName: "your-key-pair" # Replace with your Key Pair name
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: "Name"
          Value: "MyWebServer"

  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow SSH and HTTP traffic"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"

Outputs:
  InstancePublicIP:
    Value: !GetAtt MyEC2Instance.PublicIp
    Description: Public IP address of the EC2 instance.
  InstanceID:
    Value: !Ref MyEC2Instance
    Description: Instance ID of the EC2 instance.
